---
title: "Real data analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Real data analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  comment = "#>",
  fig.width = 6,
  fig.height = 4
)
options(tibble.print_min = 4L, tibble.print_max = 4L)
```

```{r echo = FALSE}
library(sdp)
```

## Example: lithium_battery data

We use `lithium_battery` data as a example.

```{r warning=FALSE}
str(lithium_battery)
lion_battery = list(lithium_battery[[1]])
```


```{r}
plot_path(lion_battery) + 
  # scale_color_discrete() +
  theme_bw() + 
  theme(panel.grid = element_blank()) 
```

## Inference

For this section, we provide a tutorial for parameter estimates using MLE and Bayesian methods. Both methods are integrated in the `sta_infer()` function and just need to be set in the `"method"`. 

### MLE

```{r warning=FALSE}
# MLE ========
mle_fit = sta_infer(method = "MLE", process = "Wiener", type = "classical",
                    data = lion_battery)
mle_fit
Reliability(t = 100, threshold = lithium_battery[[2]][1],par = mle_fit[,2],
            process = "Wiener",type = "classical")
Reliability_cowplot(R_time = 1:300, sum_para = mle_fit, threshold = lithium_battery[[2]],
                               process = "Wiener", type = "classical")
```

```{r   fig.width = 6,fig.height = 6}
rul2 = RUL(t = 1:100, cur_time = 30, threshold = lithium_battery[[2]][1], data = lithium_battery[[1]], par = mle_fit[,2], process = "Wiener", type = "classical")

RUL_plot(fut_time = c(10,15,20,25,30,50), 
         time_epoch = 1:30,
         group = 1,
         process = "Wiener", 
         type = "classical",
         threshold = lithium_battery[[2]][1],
         dat = lithium_battery[[1]],
         zlim = c(0,0.01),
         xlim = c(0,30),
         para = mle_fit[,2],
         real_RUL=c(NA,NA,NA,NA,NA,NA))
```






